source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RYImageView_Example', :exclusive => true do
  pod "RYImageView", :path => "../"
end

target 'RYImageView_Tests', :exclusive => true do
  pod "RYImageView", :path => "../"

  
end
